
name: update release version

on: 
  schedule:
  - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell
        run: |
          bash getRelease.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update release version
